# Rest Client

### create a user

POST https://api.acme.com/users
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password",
    "name": "Test User"
}

### list users

GET https://api.acme.com/users
Content-Type: application/json

### acme web

GET https://www.acme.com/
