# Rest Client

### create a user

POST http://localhost:8080/users
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password",
    "name": "Test User"
}

### list users

GET http://localhost:8080/users
Content-Type: application/json
